name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install NDK 27
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.12077973"
          ls $ANDROID_HOME/ndk/

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - run: flutter pub get

      - name: Fix NDK
        run: |
          NDK_VER=27.0.12077973
          NDK_PATH=$ANDROID_HOME/ndk/$NDK_VER
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "ndk.dir=$NDK_PATH" >> android/local.properties
          cat android/local.properties
          SWEPH=$(find $HOME/.pub-cache -type d -name "sweph-*" | head -n 1)
          echo "Fixing $SWEPH"
          sed -i "s/28.7.33676358/$NDK_VER/g" $SWEPH/android/build.gradle
          sed -i "s/28.1.13356709/$NDK_VER/g" $SWEPH/android/build.gradle
          sed -i "s/28.2.13676358/$NDK_VER/g" $SWEPH/android/build.gradle
          cat $SWEPH/android/build.gradle | grep ndk

      - run: flutter build apk --release --no-tree-shake-icons

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk