name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install NDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.1.13356709"
          NDK_PATH=$ANDROID_HOME/ndk/28.1.13356709
          echo "ANDROID_NDK_HOME=$NDK_PATH" >> $GITHUB_ENV

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'

      - run: flutter pub get

      - name: Fix NDK Problem
        run: |
          NDK_PATH=$ANDROID_HOME/ndk/28.1.13356709
          NDK_VER=28.1.13356709
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "ndk.dir=$NDK_PATH" >> android/local.properties
          SWEPH_FILE=$(find $HOME/.pub-cache -type f -name build.gradle | grep sweph | grep -v example | head -n 1)
          sed -i "s/28.7.33676358/$NDK_VER/g" "$SWEPH_FILE" || true
          sed -i "s/ndkVersion.*/ndkVersion \"$NDK_VER\"/" "$SWEPH_FILE" || true

      - run: flutter build apk --release --no-tree-shake-icons

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk